name: docker-qt5-build

on:
    push:
      paths:
        - 'docker/qt5-build/**'
    pull_request:
      paths:
        -'docker/qt5-build/**'
    
env:
  IMAGE_NAME: mltframework/qt:5.15.1-ubuntu18.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --tag $IMAGE_NAME docker/qt5-build

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mltframework/qt
